export default function Page() {
  return (
    <div 
      className="legacy-html-wrapper" 
      dangerouslySetInnerHTML={{ __html: "\n  <main class=\"wrap\">\n    <section class=\"card hero\">\n      <div>\n        <p class=\"eyebrow\">Krishiv Game Studio</p>\n        <h1>Color Switch Rush</h1>\n        <p>The game calls a color. You have one second to hit the matching pad. Every streak point makes the next round feel sharper.</p>\n        <p class=\"meta\">Designed by Krishiv PB</p>\n      </div>\n      <div class=\"controls\">\n        <button id=\"startBtn\" type=\"button\">Start Rush</button>\n        <button id=\"resetBtn\" class=\"ghost\" type=\"button\">Reset</button>\n        <a class=\"button-link ghost\" href=\"games.html#games-apps-gateway\">Back to Games Hub</a>\n      </div>\n    </section>\n\n    <section class=\"game-grid\">\n      <article class=\"card wheel-wrap\">\n        <div class=\"wheel\">\n          <div class=\"slice red\"></div>\n          <div class=\"slice blue\"></div>\n          <div class=\"slice green\"></div>\n          <div class=\"slice yellow\"></div>\n          <div class=\"wheel-center\" id=\"callout\">READY</div>\n        </div>\n      </article>\n      <article class=\"card stack\">\n        <div class=\"pill-row\">\n          <div class=\"pill\">Score: <strong id=\"score\">0</strong></div>\n          <div class=\"pill\">Best: <strong id=\"best\">0</strong></div>\n          <div class=\"pill\">Time: <strong id=\"timeLeft\">0</strong></div>\n        </div>\n        <p id=\"status\">Press start to get the first color call.</p>\n        <div class=\"pad-grid\">\n          <button class=\"pad red\" data-color=\"red\" type=\"button\">Red</button>\n          <button class=\"pad blue\" data-color=\"blue\" type=\"button\">Blue</button>\n          <button class=\"pad green\" data-color=\"green\" type=\"button\">Green</button>\n          <button class=\"pad yellow\" data-color=\"yellow\" type=\"button\">Yellow</button>\n        </div>\n      </article>\n    </section>\n  </main>\n  \n  \n" }} 
      suppressHydrationWarning 
    />
  );
}
