export default function Page() {
  return (
    <div 
      className="legacy-html-wrapper" 
      dangerouslySetInnerHTML={{ __html: "\n  <main class=\"wrap\">\n    <section class=\"card\">\n      <h1>BazaarBlitz Prime</h1>\n      <p>Interactive shopping app inspired by marketplace flow. Search, filter, cart, coupon, and simulated checkout.</p>\n      <p>Created by Krishiv PB</p>\n      <a href=\"index.html#app-verse\">Back to Apps Galaxy</a>\n    </section>\n\n    <section class=\"card grid-head\">\n      <input id=\"searchInput\" placeholder=\"Search products...\" />\n      <select id=\"categorySelect\">\n        <option value=\"all\">All Categories</option>\n        <option value=\"gaming\">Gaming</option>\n        <option value=\"school\">School</option>\n        <option value=\"creator\">Creator</option>\n        <option value=\"tech\">Tech</option>\n      </select>\n      <select id=\"sortSelect\">\n        <option value=\"featured\">Sort: Featured</option>\n        <option value=\"price-low\">Sort: Price Low</option>\n        <option value=\"price-high\">Sort: Price High</option>\n        <option value=\"rating\">Sort: Rating</option>\n      </select>\n      <button id=\"resetBtn\" type=\"button\">Reset</button>\n    </section>\n\n    <section class=\"layout\">\n      <article class=\"card\">\n        <h2>Shop Deck</h2>\n        <div id=\"products\" class=\"products\"></div>\n      </article>\n\n      <aside class=\"card\">\n        <h2>Cart</h2>\n        <div id=\"cartItems\"></div>\n        <div class=\"totals\">\n          <div class=\"row\"><span>Subtotal</span><strong id=\"subtotal\">Rs 0</strong></div>\n          <div class=\"row\"><span>Shipping</span><strong id=\"shipping\">Rs 0</strong></div>\n          <div class=\"row\"><span>Discount</span><strong id=\"discount\">Rs 0</strong></div>\n          <div class=\"row\"><span>Total</span><strong id=\"total\">Rs 0</strong></div>\n          <div class=\"row\">\n            <input id=\"couponInput\" placeholder=\"Coupon code\" style=\"flex:1;\" />\n            <button id=\"applyCouponBtn\" type=\"button\">Apply</button>\n          </div>\n          <button id=\"checkoutBtn\" class=\"btn-main\" type=\"button\" style=\"width:100%;\">Checkout</button>\n        </div>\n      </aside>\n    </section>\n\n    <section class=\"card\">\n      <h2>Order History</h2>\n      <p class=\"small\">Recent simulated orders stored in your browser.</p>\n      <div id=\"orderHistory\"></div>\n    </section>\n  </main>\n\n  \n  \n" }} 
      suppressHydrationWarning 
    />
  );
}
