export default function Page() {
  return (
    <div 
      className="legacy-html-wrapper" 
      dangerouslySetInnerHTML={{ __html: "\n  <main class=\"wrap\">\n    <section class=\"card\">\n      <h1>Idea Lab AI</h1>\n      <p class=\"meta\">Created by Krishiv PB | AI idea generation + backend idea database</p>\n      <a href=\"index.html#projects\">Back to portfolio</a>\n    </section>\n\n    <section class=\"grid\">\n      <article class=\"card\">\n        <h2>Generate With AI</h2>\n        <div class=\"meta\">Describe what kind of app you want to build.</div>\n        <p><input id=\"goal\" placeholder=\"Goal (example: app to help students revise fast)\" maxlength=\"140\" /></p>\n        <p><input id=\"audience\" placeholder=\"Audience (example: grade 6-10 students)\" maxlength=\"80\" /></p>\n        <p><input id=\"constraints\" placeholder=\"Constraints (example: mobile first, no login)\" maxlength=\"120\" /></p>\n        <p>\n          <label for=\"ideaCount\" class=\"meta\">How many ideas</label>\n          <select id=\"ideaCount\">\n            <option value=\"1\">1 idea</option>\n            <option value=\"2\">2 ideas</option>\n            <option value=\"3\" selected>3 ideas</option>\n            <option value=\"4\">4 ideas</option>\n            <option value=\"5\">5 ideas</option>\n            <option value=\"6\">6 ideas</option>\n          </select>\n        </p>\n        <div class=\"row\">\n          <button id=\"generateBtn\" class=\"btn primary\" type=\"button\">Generate Idea</button>\n          <button id=\"saveBtn\" class=\"btn\" type=\"button\">Save To Database</button>\n          <button id=\"copyBtn\" class=\"btn\" type=\"button\">Copy Result</button>\n        </div>\n        <div class=\"row\">\n          <button type=\"button\" class=\"btn templateBtn\" data-template=\"quiz app for kids\">Quiz App</button>\n          <button type=\"button\" class=\"btn templateBtn\" data-template=\"habit and focus coach\">Habit Coach</button>\n          <button type=\"button\" class=\"btn templateBtn\" data-template=\"study planner with rewards\">Study Rewards</button>\n        </div>\n        <p id=\"genMode\" class=\"meta\"></p>\n        <textarea id=\"result\" placeholder=\"AI suggestion appears here...\"></textarea>\n        <div id=\"ideasGenerated\"></div>\n      </article>\n\n      <article class=\"card\">\n        <h2>Saved Ideas</h2>\n        <p><input id=\"ideasSearch\" placeholder=\"Search saved ideas...\" /></p>\n        <div id=\"ideasList\"></div>\n      </article>\n    </section>\n  </main>\n\n  \n\r\n  \r\n" }} 
      suppressHydrationWarning 
    />
  );
}
