export default function Page() {
  return (
    <div 
      className="legacy-html-wrapper" 
      dangerouslySetInnerHTML={{ __html: "<main class=\"concept-wrap\"><section class=\"concept-shell concept-hero\"><span id=\"appCategory\" class=\"concept-kicker\"></span><h1 id=\"appTitle\" class=\"concept-title\"></h1><p id=\"appLead\" class=\"concept-lead\"></p><div class=\"concept-meta\"><span class=\"concept-pill\">Starter app page</span><a class=\"concept-link\" href=\"index.html#app-verse\">Back to Apps Galaxy</a></div></section><section class=\"concept-grid\"><section class=\"concept-shell\"><h2>Add Group Plan</h2><div class=\"concept-form-grid\"><div><label id=\"titleLabel\" for=\"entryTitle\"></label><input id=\"entryTitle\" /></div><div><label id=\"metaLabel\" for=\"entryMeta\"></label><input id=\"entryMeta\" /></div><div><label for=\"entryState\">Group style</label><select id=\"entryState\"></select></div><div class=\"concept-full\"><label id=\"notesLabel\" for=\"entryNotes\"></label><textarea id=\"entryNotes\"></textarea></div></div><div class=\"concept-actions\"><button id=\"addEntryBtn\" class=\"concept-btn-primary\" type=\"button\"></button><button id=\"seedEntryBtn\" class=\"concept-btn-secondary\" type=\"button\"></button></div></section><section class=\"concept-shell\"><h2>Split Ideas</h2><div id=\"seedChips\" class=\"concept-seeds\"></div><p id=\"helperCopy\"></p></section></section><section class=\"concept-shell\"><div class=\"concept-board-head\"><h2 id=\"boardTitle\"></h2><input id=\"searchInput\" type=\"search\" /></div><div class=\"concept-stats\"><div class=\"concept-stat\"><strong id=\"totalCount\">0</strong><span>Group sets</span></div><div class=\"concept-stat\"><strong id=\"pinnedCount\">0</strong><span>Priority sets</span></div><div class=\"concept-stat\"><strong id=\"doneCount\">0</strong><span>Already used</span></div></div><div id=\"entryList\" class=\"concept-list\"></div></section></main>" }} 
      suppressHydrationWarning 
    />
  );
}
