export default function Page() {
  return (
    <div 
      className="legacy-html-wrapper" 
      dangerouslySetInnerHTML={{ __html: "\n  <main class=\"concept-wrap\">\n    <section class=\"concept-shell concept-hero\">\n      <span id=\"appCategory\" class=\"concept-kicker\"></span>\n      <h1 id=\"appTitle\" class=\"concept-title\"></h1>\n      <p id=\"appLead\" class=\"concept-lead\"></p>\n      <div class=\"concept-meta\">\n        <span class=\"concept-pill\">Starter app page</span>\n        <a class=\"concept-link\" href=\"index.html#app-verse\">Back to Apps Galaxy</a>\n      </div>\n    </section>\n    <section class=\"concept-grid\">\n      <section class=\"concept-shell\">\n        <h2>Create Entry</h2>\n        <div class=\"concept-form-grid\">\n          <div><label id=\"titleLabel\" for=\"entryTitle\"></label><input id=\"entryTitle\" /></div>\n          <div><label id=\"metaLabel\" for=\"entryMeta\"></label><input id=\"entryMeta\" /></div>\n          <div><label for=\"entryState\">Stage</label><select id=\"entryState\"></select></div>\n          <div class=\"concept-full\"><label id=\"notesLabel\" for=\"entryNotes\"></label><textarea id=\"entryNotes\"></textarea></div>\n        </div>\n        <div class=\"concept-actions\"><button id=\"addEntryBtn\" class=\"concept-btn-primary\" type=\"button\"></button><button id=\"seedEntryBtn\" class=\"concept-btn-secondary\" type=\"button\"></button></div>\n      </section>\n      <section class=\"concept-shell\"><h2>Quick Ideas</h2><div id=\"seedChips\" class=\"concept-seeds\"></div><p id=\"helperCopy\"></p></section>\n    </section>\n    <section class=\"concept-shell\"><div class=\"concept-board-head\"><h2 id=\"boardTitle\"></h2><input id=\"searchInput\" type=\"search\" /></div><div class=\"concept-stats\"><div class=\"concept-stat\"><strong id=\"totalCount\">0</strong><span>Total entries</span></div><div class=\"concept-stat\"><strong id=\"pinnedCount\">0</strong><span>Pinned</span></div><div class=\"concept-stat\"><strong id=\"doneCount\">0</strong><span>Done</span></div></div><div id=\"entryList\" class=\"concept-list\"></div></section>\n  </main>\n  \n  \n  \n" }} 
      suppressHydrationWarning 
    />
  );
}
