export default function Page() {
  return (
    <div 
      className="legacy-html-wrapper" 
      dangerouslySetInnerHTML={{ __html: "\n  <main class=\"wrap\">\n    <section class=\"card\">\n      <h1>StoryForge Studio</h1>\n      <p class=\"meta\">Build creative mini stories with genre templates, twists, and endings.</p>\n      <p class=\"meta\">Created by Krishiv PB</p>\n      <a href=\"index.html#app-verse\">Back to Apps Galaxy</a>\n    </section>\n\n    <section class=\"card grid\">\n      <article>\n        <h2>Create Story</h2>\n        <input id=\"heroInput\" placeholder=\"Main hero name\" style=\"margin-bottom:8px;\" />\n        <input id=\"placeInput\" placeholder=\"Place (city, planet, forest...)\" style=\"margin-bottom:8px;\" />\n        <select id=\"genreSelect\" style=\"margin-bottom:8px;\">\n          <option value=\"adventure\">Adventure</option>\n          <option value=\"mystery\">Mystery</option>\n          <option value=\"future\">Future Tech</option>\n          <option value=\"fantasy\">Fantasy</option>\n        </select>\n        <select id=\"twistSelect\" style=\"margin-bottom:8px;\">\n          <option value=\"hidden-map\">Hidden map appears</option>\n          <option value=\"secret-friend\">A secret friend helps</option>\n          <option value=\"time-loop\">Time loop starts</option>\n          <option value=\"final-clue\">Final clue is in plain sight</option>\n        </select>\n        <button id=\"generateBtn\" class=\"btn-main\" type=\"button\">Generate Story</button>\n      </article>\n      <article>\n        <h2>Output</h2>\n        <textarea id=\"result\"></textarea>\n        <div style=\"display:flex; gap:8px; margin-top:8px;\">\n          <button id=\"copyBtn\" type=\"button\">Copy</button>\n          <button id=\"saveBtn\" type=\"button\">Save Story</button>\n        </div>\n      </article>\n    </section>\n\n    <section class=\"card\">\n      <h2>Saved Stories</h2>\n      <div id=\"stories\"></div>\n    </section>\n  </main>\n\n  \n  \n" }} 
      suppressHydrationWarning 
    />
  );
}
