export default function Page() {
  return (
    <div 
      className="legacy-html-wrapper" 
      dangerouslySetInnerHTML={{ __html: "\n  <main class=\"wrap\">\n    <section class=\"card\">\n      <h1>Expense Tracker</h1>\n      <p class=\"meta\">Created by Krishiv PB</p>\n      <a href=\"index.html#projects\">Back to portfolio</a>\n    </section>\n\n    <section class=\"card\">\n      <div class=\"row\">\n        <input id=\"title\" placeholder=\"Entry title\" maxlength=\"60\" />\n        <input id=\"amount\" type=\"number\" step=\"0.01\" placeholder=\"Amount\" />\n        <select id=\"type\"><option value=\"expense\">Expense</option><option value=\"income\">Income</option></select>\n        <select id=\"category\">\n          <option>General</option><option>Food</option><option>Study</option><option>Travel</option><option>Entertainment</option><option>Savings</option>\n        </select>\n        <input id=\"entryDate\" type=\"date\" />\n        <button class=\"btn primary\" id=\"addBtn\">Add</button>\n      </div>\n    </section>\n\n    <section class=\"card\">\n      <div class=\"stats\">\n        <article class=\"stat\"><strong id=\"bal\">0.00</strong><span class=\"meta\">Balance</span></article>\n        <article class=\"stat\"><strong id=\"inc\">0.00</strong><span class=\"meta\">Income</span></article>\n        <article class=\"stat\"><strong id=\"exp\">0.00</strong><span class=\"meta\">Expense</span></article>\n        <article class=\"stat\"><strong id=\"monthSpend\">0.00</strong><span class=\"meta\">This Month Spend</span></article>\n      </div>\n      <div class=\"row\" style=\"margin-top:10px;\">\n        <input id=\"search\" placeholder=\"Search title/category...\" />\n        <select id=\"filterType\"><option value=\"all\">All Types</option><option value=\"income\">Income</option><option value=\"expense\">Expense</option></select>\n        <button id=\"exportBtn\" class=\"btn\">Export CSV</button>\n      </div>\n    </section>\n\n    <section class=\"card\">\n      <table>\n        <thead><tr><th>Title</th><th>Category</th><th>Type</th><th>Date</th><th>Amount</th><th></th></tr></thead>\n        <tbody id=\"rows\"></tbody>\n      </table>\n    </section>\n  </main>\n  \n\n  \n" }} 
      suppressHydrationWarning 
    />
  );
}
