export default function Page() {
  return (
    <div 
      className="legacy-html-wrapper" 
      dangerouslySetInnerHTML={{ __html: "\n  <main class=\"wrap\">\n    <section class=\"card\">\n      <h1>Habit Streak Tracker</h1>\n      <p>Create habits, track streaks, filter by category, and export/import your progress.</p>\n      <p>Created by Krishiv PB</p>\n      <a href=\"index.html#projects\">Back to portfolio</a>\n    </section>\n\n    <section class=\"card\">\n      <h2>Add Habit</h2>\n      <div class=\"row\">\n        <input id=\"habitInput\" maxlength=\"60\" placeholder=\"Example: 30 min coding practice\" />\n        <select id=\"habitCategory\">\n          <option value=\"Study\">Study</option>\n          <option value=\"Health\">Health</option>\n          <option value=\"Fitness\">Fitness</option>\n          <option value=\"Focus\">Focus</option>\n          <option value=\"Custom\">Custom</option>\n        </select>\n        <button id=\"addHabitBtn\" class=\"btn primary\" type=\"button\">Add Habit</button>\n      </div>\n      <div class=\"row\" style=\"margin-top:8px;\">\n        <input id=\"searchInput\" placeholder=\"Search habits...\" />\n        <select id=\"categoryFilter\">\n          <option value=\"all\">All Categories</option>\n          <option value=\"Study\">Study</option>\n          <option value=\"Health\">Health</option>\n          <option value=\"Fitness\">Fitness</option>\n          <option value=\"Focus\">Focus</option>\n          <option value=\"Custom\">Custom</option>\n        </select>\n        <button id=\"exportBtn\" class=\"btn soft\" type=\"button\">Export</button>\n        <button id=\"importBtn\" class=\"btn soft\" type=\"button\">Import</button>\n        <input id=\"importFile\" type=\"file\" accept=\"application/json\" hidden />\n      </div>\n    </section>\n\n    <section class=\"card\">\n      <h2>Stats</h2>\n      <div class=\"stats\">\n        <article class=\"stat\"><strong id=\"totalHabits\">0</strong><span class=\"meta\">Total Habits</span></article>\n        <article class=\"stat\"><strong id=\"bestStreak\">0</strong><span class=\"meta\">Best Streak</span></article>\n        <article class=\"stat\"><strong id=\"doneToday\">0</strong><span class=\"meta\">Done Today</span></article>\n      </div>\n    </section>\n\n    <section class=\"card\">\n      <h2>Your Habits</h2>\n      <div id=\"habitList\"></div>\n    </section>\n  </main>\n\n  \n\n  \n" }} 
      suppressHydrationWarning 
    />
  );
}
